### ISSUE TITLE
The results of clustering

### ISSUE THREAD

**Issue by Shinta2018** [yaodi833/trajectory2vec#2]
Hi Di Yao!

Many thanks for your codes.
Here is a question on the codes. The output of the clustering is the cluster of the moving behavior vector set. How do you get the clusters of the trajectories, like in the shape [[time1, lon1, lat1], [time2, lon2, lat2], ...]?

Thanks in advance. Cheers!

**Comment by yaodi833** [comment]
Thanks for your interest. This repository is a lite version to show the main idea of the paper. For further usage, you should maintain a unique trajectory id for original trajectory, moving behavior sequence and trajectory embedding. Then, the clustering result can be mapped from the embedding to original trajectory.

**Comment by Shinta2018** [comment]
I see. Thanks!
